CREATE TABLE FIELDS (
	ID INT(11) AUTO_INCREMENT PRIMARY KEY,
	FIELD_NAME VARCHAR(255),
	FIELD_TYPE VARCHAR(255)
);

CREATE TABLE PROJECT_MEMBERS (
	ID INT(11) AUTO_INCREMENT PRIMARY KEY,
	USER_ID INT(11),
	PROJECT_ID INT(11),
	ROLE INT(11)
);

CREATE TABLE PROJECT_MENU_CONTENTS (
	ID INT(11) AUTO_INCREMENT PRIMARY KEY,
	PROJECT_MENU_ID INT(11),
	PORJECT_MENU_CONTENT_NAME VARCHAR(255),
	PROJECT_MENU_CONTENT_FIELD INT(11),
	PORJECT_MENU_CONTENT_DEFAULT VARCHAR(255),
	PROJECT_MENU_CONTENT_EXPLANATION VARCHAR(255)
);

CREATE TABLE PROJECT_MENUS (
	ID INT(11) AUTO_INCREMENT PRIMARY KEY,
	PROJECT_ID INT(11),
	PROJECT_MENU_NAME VARCHAR(255),
	PROJECT_MENU_INDEX INT(11)
	
);

CREATE TABLE PROJECTS (
	ID INT(11) AUTO_INCREMENT PRIMARY KEY,
	USER_ID INT(11),
	PROJECT_NAME VARCHAR(255),
	PROJECT_EXPIRATE_DATE DATE
);

CREATE TABLE USER(
	ID INT(11) AUTO_INCREMENT PRIMARY KEY,
	USER_NAME VARCHAR(255),
	USER_EMAIL VARCHAR(255),
	USER_PASSWORD  VARCHAR(255)
);


INSERT INTO USER (USER_NAME, USER_EMAIL, USER_PASSWORD) VALUES ('석진철', 'tjrwlscjf13@naver.com', '');

INSERT INTO FIELDS (FIELD_NAME, FIELD_TYPE) VALUES ('text', 'TextField');
INSERT INTO FIELDS (FIELD_NAME, FIELD_TYPE) VALUES ('number', 'NumberField');
INSERT INTO FIELDS (FIELD_NAME, FIELD_TYPE) VALUES ('date', 'DateField');
INSERT INTO FIELDS (FIELD_NAME, FIELD_TYPE) VALUES ('combo', 'ComboField');
INSERT INTO FIELDS (FIELD_NAME, FIELD_TYPE) VALUES ('slider', 'SliderField');
