#USER
INSERT INTO USER (USER_NAME, USER_EMAIL, USER_PASSWORD) VALUES ('석진철', 'tjrwlscjf13@naver.com', '');

#FIELDS
INSERT INTO FIELDS (FIELD_NAME, FIELD_TYPE) VALUES ('text', 'TextField');
INSERT INTO FIELDS (FIELD_NAME, FIELD_TYPE) VALUES ('number', 'NumberField');
INSERT INTO FIELDS (FIELD_NAME, FIELD_TYPE) VALUES ('date', 'DateField');
INSERT INTO FIELDS (FIELD_NAME, FIELD_TYPE) VALUES ('combo', 'ComboField');
INSERT INTO FIELDS (FIELD_NAME, FIELD_TYPE) VALUES ('slider', 'SliderField');
